app_id="xyz.toastxc.Bazaar"
app_name="Bazaar"
profile="release"

permissions = [
    "--share=network",
    "--socket=fallback-x11",
    "--socket=wayland",
    "--device=dri"
]

[desktopfile]
terminal= false


